title: "Brandon Fricker- Behavioral Neuroscientist"
name: "Brandon Fricker"
description: >-
  Postdoctoral fellow in The Elya Lab at Harvard University. I study behavioral manipulation in Zombie Flies.
url: "https://bfnerdly.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

author:
  name: "Brandon Fricker"
  avatar: "/assets/images/headshot.jpg"
  bio: "Postdoctoral fellow studying Zombie flies."

nav:
  - title: "About"
    url: /about/
  - title: "Publications"
    url: /publications/
  - title: "Contact"
    url: /contact/

markdown: kramdown